baseURL: 'https://zz-jason.github.io/'
title: Jian Zhang
paginate: 5
enableEmoji: true
hasCJKLanguage: true
googleAnalytics: "UA-67872953-1"
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: archives
      name: Archives
      url: /posts/
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4

Author:
  name: Jian
  avatar: /img/avatar.png

Params:
  env: 'production'

  # for the theme
  defaultTheme: light
  disableThemeToggle: true

  # for homepage
  homeInfoParams:
    # Title:
    Content: "Why did you want to climb Mount Everest?\n\nBecause it’s there."
    # socialIcons:
    #   - name: twitter
    #     url: "https://twitter.com/zhangjian1012"
    #   - name: linkedin
    #     url: "https://www.linkedin.com/in/zhangjian1012/"
    #   - name: github
    #     url: "https://github.com/zz-jason"
    #   - name: email
    #     url: "mailto:zjsariel@gmail.com"

  # for pages
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  author: 'Jian'
  showtoc: true
  tocopen: false
  comments: true
