baseURL: 'https://zz-jason.github.io/'
title: Jian Zhang's Blog
paginate: 5
enableEmoji: true
hasCJKLanguage: true
googleAnalytics: "UA-67872953-1"
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: archives
      name: Archives
      url: /posts/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 4

Author:
  name: Jian Zhang
  avatar: /img/avatar.png

Params:
  env: 'production'
  ShowReadingTime: true
  ShowShareButtons: true
  author: 'Jian Zhang'
  showtoc: true
  tocopen: false
  comments: true
  defaultTheme: light
  disableThemeToggle: true
  homeInfoParams:
    Title: Hi there 👋
    Content: "Welcome to my blog, you can also find me in the following social icons:"
  socialIcons:
    - name: twitter
      url: "https://twitter.com/zhangjian1012"
    - name: linkedin
      url: "https://www.linkedin.com/in/zhangjian1012/"
    - name: github
      url: "https://github.com/zz-jason"
